let list = [
    [
        {bet: 'bet bet bet', translate: 'робити ставку'},
        {burst: 'burst burst burst', translate: 'лопатися, розриватися'},
        {cast: 'cast cast cast', translate: 'кидати'},
        {cost: 'cost cost cost', translate: 'коштувати'},
        {cut: 'cut cut cut', translate: 'різати'},
        {fit: 'fit fit fit', translate: 'підходити, відповідати'},
        {hit: 'hit hit hit', translate: 'бити'},
        {hurt: 'hurt hurt hurt', translate: 'пошкоджувати'},
        {let: 'let let let', translate: 'дозволяти'},
        {put: 'put put put', translate: 'поміщати'},
        {quit: 'quit quit quit', translate: 'звільнятися'},
        {set: 'set set set', translate: 'встановлювати'},
        {shut: 'shut shut shut', translate: 'закривати'},
        {split: 'split split split', translate: 'розколювати, розщеплювати'},
        {spread: 'spread spread spread', translate: 'розмазувати, поширювати'}
    ],
    [
        {come: 'come came come', translate: 'приходити'},
        {become: 'become became become', translate: 'ставати'},
        {run: 'run ran run', translate: 'бігти'},
    ],
    [
        {break: 'break broke broken', translate: '(з)ламати'},
        {choose: 'choose chose chosen', translate: 'вибирати'},
        {forget: 'forget forgot forgotten', translate: 'забувати'},
        {freeze: 'freeze froze frozen', translate: 'замерзати, заморожувати'},
        {get: 'get got gotten', translate: 'отримувати'},
        {speak: 'speak spoke spoken', translate: 'розмовляти'},
        {steal: 'steal stole stolen', translate: 'красти'},
        {tear: 'tear tore torn', translate: 'розривати'},
        {wake: 'wake woke woken', translate: 'будити'},
        {wear: 'wear wore worn', translate: 'надягати'},
        {$$$1: '$$$ $$$ $$$', translate: '$$$'},
        {drive: 'drive drove driven', translate: 'вести машину'},
        {ride: 'ride rode ridden', translate: 'їхати верхи'},
        {rise: 'rise rose risen', translate: 'піднімати(ся)'},
        {write: 'write wrote written', translate: 'писати'},
        {$$$2: '$$$ $$$ $$$', translate: '$$$'},
        {blow: 'blow blew blown', translate: 'дути'},
        {fly: 'fly flew flown', translate: 'літати'},
        {grow: 'grow grEw grown', translate: 'рости'},
        {know: 'know knew known', translate: 'знати'},
        {throw: 'throw threw thrown', translate: 'кидати'},   
    ],
    [
        {bite: 'bite bit bitten', translate: 'кусати'},
        {hide: 'hide hid hidden', translate: 'ховати(ся)'},
        {eat: 'eat ate eaten', translate: 'їсти'},
        {fall: 'fall fell fallen', translate: 'падати'},
        {forbid: 'forbid forbade forbidden', translate: 'забороняти'},
        {forgive: 'forgive forgave forgiven', translate: 'прощати'},
        {give: 'give gave given', translate: 'давати'},
        {see: 'see saw seen', translate: 'бачити'},
        {shake: 'shake shook shaken', translate: 'трясти'},
        {take: 'take took taken', translate: 'брати'},
    ]
]